---
- name: check cert
  stat:
    path: '/etc/letsencrypt/live/{{ certbot_domain }}/fullchain.pem'
  register: cert

- block:
  - name: 認証ファイルの作成
    blockinfile:
      path: /tmp/cloudflare_secret
      block: |
        dns_cloudflare_email = {{ dns_cloudflare_email }}
        dns_cloudflare_api_key = {{ dns_cloudflare_api_key }}
      create: yes
  - name: certbotコマンドの実行
    command: |
      certbot certonly
      -n
      --email {{ dns_cloudflare_email }}
      --agree-tos
      --dns-cloudflare
      --dns-cloudflare-credentials /tmp/cloudflare_secret
      --dns-cloudflare-propagation-seconds 30
      -d *.{{ certbot_domain }}
      -d {{ certbot_domain }}

  - name: 認証ファイルの削除
    file:
      path: /tmp/cloudflare_secret
      state: absent

  when: not cert.stat.exists and dns_cloudflare_email is defined and dns_cloudflare_api_key is defined
