---
database:
  password: password
virtual_mailbox_base: /var/vmail
virtual_mailbox_domains: example.com. example.net
virtual_mailbox_maps:
  - address: example@example.com
    destination: example.com/example/
  - address: '(example|info)@example\.net$'
    destination: example.net/example/
    is_regexp: 1
dovecot:
  users:
    - username: example
      domain: example.com
      password: '{PLAIN}password'
    - username: example
      domain: example.net
      password: '{PLAIN}password'
rspamd:
  domain: example.com
