---
# インストールするパッケージ
base_packages:
- curl
- git
- language-pack-ja
- mailutils
- postfix
- vim

#追加でパッケージをインストールする場合は定義
#add_packages:
#- apache2

#サーバにホスト名を設定する場合は定義
#hostname: '{{ inventory_hostname }}'

#Postfixのmain.cfに追加設定をする場合はkey / valueの配列を定義
#postfix_main_config:
#  relayhost: 'mail.example.com'
#  myhostname: '{{ hostname }}.example.com'
#  mydestination: '$myhostname, {{ hostname }}, localhost.localdomain, localhost'
