- name: archユーザの作成
  user:
    name: arch
    groups: wheel
    password: ''
    append: yes

- name: archユーザにssh鍵を設定
  authorized_key:
    user: arch
    state: present
    key: https://github.com/eggpan.keys
  when: not ansible_check_mode

- name: wheelグループに対してsudo許可
  lineinfile:
    path: /etc/sudoers
    regexp: '%wheel.+NOPASSWD'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: タイムゾーンの設定
  timezone:
    name: Asia/Tokyo

- name: ロケールの設定
  locale_gen:
    name: '{{ item }}'
  loop:
  - en_US.UTF-8
  - ja_JP.UTF-8
