---
- name: nginx defaultサイトの削除
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: sites-available/rspamd の作成
  ansible.builtin.template:
    src: nginx/rspamd.j2
    dest: /etc/nginx/sites-available/rspamd

- name: sites-available/rspamd の有効化
  ansible.builtin.file:
    src: /etc/nginx/sites-available/rspamd
    dest: /etc/nginx/sites-enabled/rspamd
    state: link
  notify: restart nginx
