---
- name: add Rspamd GPG key
  ansible.builtin.apt_key:
    url: https://rspamd.com/apt-stable/gpg.key

- name: add Rspamd repository
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
  loop:
    - "deb [arch=amd64] http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"
    - "deb-src [arch=amd64] http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"

- name: 各種パッケージのインストール
  ansible.builtin.apt:
    name:
      - dovecot-imapd
      - dovecot-mysql
      - dovecot-pop3d
      - mariadb-server
      - nginx
      - postfix
      - postfix-mysql
      - python3-certbot-dns-cloudflare
      - redis
      - rspamd
    force_apt_get: yes
    update_cache: yes
