---
- name: keyfile用のディレクトリ作成
  ansible.builtin.file:
    path: /etc/opendkim/keys/{{ item.domain }}
    state: directory

- name: keyfileの作成
  ansible.builtin.command: opendkim-genkey --domain={{ item.domain }} --selector={{ item.selector }} --directory=/etc/opendkim/keys/{{ item.domain }}
  args:
    creates: /etc/opendkim/keys/{{ item.domain }}/{{ item.selector }}.private
  notify: restart opendkim

- name: keyfileのownerをopendkimに変更
  ansible.builtin.file:
    path: /etc/opendkim/keys/{{ item.domain }}/{{ item.selector }}.private
    owner: opendkim
  ignore_errors: '{{ ansible_check_mode }}'

- name: txtのパーミッションを644に変更
  ansible.builtin.file:
    path: /etc/opendkim/keys/{{ item.domain }}/{{ item.selector }}.txt
    mode: 0644
  ignore_errors: '{{ ansible_check_mode }}'
