---
- name: dovecot mail_location設定
  community.general.ini_file:
    path: /etc/dovecot/conf.d/10-mail.conf
    section: null
    option: mail_location
    value: "maildir:{{ virtual_mailbox_base }}/%d/%n"
  notify: restart dovecot

- name: dovecot auth-sql.conf.extの有効化
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '#(!include auth-sql\.conf\.ext)'
    line: '\1'
    backrefs: yes
  notify: restart dovecot
  ignore_errors: '{{ ansible_check_mode }}'

- name: dovecot postfix連携用の設定
  ansible.builtin.copy:
    dest: /etc/dovecot/conf.d/10-postfix-auth.conf
    content: |
      service auth {
        unix_listener /var/spool/postfix/private/auth {
          mode = 0660
          user = postfix
          group = postfix
        }
      }

- name: dovecot imapメールボックスの設定
  ansible.builtin.copy:
    src: 15-mailboxes.conf
    dest: /etc/dovecot/conf.d/15-mailboxes.conf
  notify: restart dovecot

- name: dovecot 認証用sqlの設定
  ansible.builtin.blockinfile:
    path: /etc/dovecot/dovecot-sql.conf.ext
    block: |
      driver = mysql
      connect = host=localhost dbname=mail user=mail password=password
      default_pass_scheme = PLAIN
      password_query = SELECT username AS user, domain, password FROM users WHERE username = '%n' AND domain = '%d' AND is_active = 1
      user_query = SELECT CONCAT('{{ virtual_mailbox_base }}/', domain, '/', username, '/') as home, 5000 as uid, 5000 as gid FROM users WHERE username = '%n' AND domain = '%d' AND is_active = 1
  notify: restart dovecot
  ignore_errors: '{{ ansible_check_mode }}'

- name: dovecot 認証ユーザーの追加
  ansible.builtin.include_tasks: config_dovecot_user.yml
  loop: '{{ dovecot.users }}'

- name: dovecot ssl証明書の設定
  ansible.builtin.blockinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    block: '{{ dovecot.certs }}'
    create: yes
  when: dovecot.certs is defined
  notify: restart dovecot
