---
- name: postfix/main.cf の作成
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix

- name: postfix/master.cf submissionポートの設定
  ansible.builtin.blockinfile:
    path: /etc/postfix/master.cf
    insertbefore: '^#smtps'
    block: |
      submission inet n       -       y       -       -       smtpd
        -o syslog_name=postfix/submission
        -o smtpd_tls_security_level=encrypt
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_tls_auth_only=yes
        -o smtpd_client_restrictions=permit_sasl_authenticated,reject
        -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
        -o milter_macro_daemon_name=ORIGINATING
  notify: restart postfix
  ignore_errors: '{{ ansible_check_mode }}'

- name: メールボックス用ディレクトリの作成
  ansible.builtin.file:
    path: '{{ virtual_mailbox_base }}'
    state: directory
    owner: "5000"
    group: "5000"
    mode: 0700

- name: header_checks.regexp の作成
  ansible.builtin.copy:
    dest: /etc/postfix/header_checks.regexp
    content : '{{ header_checks | default("") }}'
  notify: restart postfix

- name: virtual_mailbox_maps.cf の作成
  ansible.builtin.copy:
    dest: /etc/postfix/virtual_mailbox_maps.cf
    content: |
      user = mail
      password = password
      hosts = 127.0.0.1
      dbname = mail
      query = SELECT destination FROM mailbox_maps
        WHERE (address = '%s' AND is_regexp = 0 AND is_active = 1) OR ('%s' REGEXP address AND is_regexp = 1 AND is_active = 1)
  notify: restart postfix

- name: maibox_mapsへのデータ追加
  ansible.builtin.include_tasks: config_postfix_maibox_map.yml
  loop: '{{ virtual_mailbox_maps }}'

- name: smtp_sasl_password_maps の作成
  ansible.builtin.copy:
    dest: /etc/postfix/smtp_sasl_password_maps
    content: '{{ smtp_sasl_password_maps }}'
    mode: 0600
  when: smtp_sasl_password_maps is defined
  notify:
    - postmap smtp_sasl_password_maps
    - restart postfix

- name: tls_server_sni_maps の作成
  ansible.builtin.copy:
    dest: /etc/postfix/tls_server_sni_maps
    content: '{{ tls_server_sni_maps }}'
    mode: 0600
  when: tls_server_sni_maps is defined
  notify:
    - postmap tls_server_sni_maps
    - restart postfix
