---
- name: dovecot mail_location設定
  ini_file:
    path: /etc/dovecot/conf.d/10-mail.conf
    section: null
    option: mail_location
    value: "maildir:/var/mail/vhosts/%d/%n"
  notify: restart dovecot

- name: dovecot auth-static.conf.extの有効化
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '#(!include auth-static\.conf\.ext)'
    line: '\1'
    backrefs: yes
  notify: restart dovecot

- name: dovecot auth-passwdfile.conf.extの有効化
  lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '#(!include auth-passwdfile\.conf\.ext)'
    line: '\1'
    backrefs: yes
  notify: restart dovecot

- name: auth-static.conf.extの設定
  blockinfile:
    path: /etc/dovecot/conf.d/auth-static.conf.ext
    block: |
      userdb {
        driver = static
        args = uid=5000 gid=5000 home=/var/mail/vhosts/%d/%n
      }

- name: dovecot postfix連携用の設定
  blockinfile:
    path: /etc/dovecot/conf.d/10-postfix-auth.conf
    create: yes
    block: |
      service auth {
        unix_listener /var/spool/postfix/private/auth {
          mode = 0660
          user = postfix
          group = postfix
        }
      }

- name: users ファイルの作成
  blockinfile:
    path: /etc/dovecot/users
    block: '{{ dovecot.users }}'
    group: dovecot
    mode: 0640
    create: yes
  when: dovecot.users is defined
  notify: restart dovecot

- name: dovecot certs の設定
  blockinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    block: '{{ dovecot.certs }}'
    create: yes
  when: dovecot.certs is defined
  notify: restart dovecot
