---
- name: opendkim keyfileの確認
  stat:
    path: '/etc/opendkim/keys/{{ item.domain }}/{{ item.selector }}.private'
  register: opndkim_keyfile

- name: keyfileの作成
  block:
    - name: keyfile用のディレクトリ作成
      file:
        path: /etc/opendkim/keys/{{ item.domain }}
        state: directory

    - name: keyfileの作成
      command: 'openssl genrsa -out /etc/opendkim/keys/{{ item.domain }}/{{ item.selector }}.private 1024'
  when: not opndkim_keyfile.stat.exists

- name: keyfileのownerをopendkimに変更
  file:
    path: '/etc/opendkim/keys/{{ item.domain }}/{{ item.selector }}.private'
    owner: opendkim
