---
- name: opendkimのコンフィグ設定
  ansible.builtin.copy:
    src: opendkim.conf
    dest: /etc/opendkim.conf

- name: ドメインごとの keyfile 作成
  include_tasks: config_opendkim_keyfile.yml
  when: opendkim_domainkeys is defined
  loop: '{{ opendkim_domainkeys }}'

- name: SigningTableの作成
  ansible.builtin.template:
    src: opendkim/SigningTable.j2
    dest: /etc/opendkim/SigningTable
  when: opendkim_domainkeys is defined

- name: KeyTableの作成
  ansible.builtin.template:
    src: opendkim/KeyTable.j2
    dest: /etc/opendkim/KeyTable
  when: opendkim_domainkeys is defined
