---
- name: 各種パッケージのインストール
  ansible.builtin.apt:
    name:
      - dovecot-imapd
      - dovecot-mysql
      - dovecot-pop3d
      - mariadb-server
      - nginx
      - postfix
      - postfix-mysql
      - python3-certbot-dns-cloudflare
      - redis
      - rspamd
    force_apt_get: yes
    update_cache: yes
