---
- name: OSの各種設定
  ansible.builtin.import_tasks: config_os.yml

- name: パッケージインストール
  ansible.builtin.import_tasks: install.yml
  tags: install

- name: certbotのコンフィグ設定
  ansible.builtin.import_tasks: config_certbot.yml
  when: >
    certbot.domains is defined
    and dns_cloudflare.email is defined
    and dns_cloudflare.api_key is defined

- name: データベースの設定
  ansible.builtin.import_tasks: config_database.yml

- name: postfixのコンフィグ設定
  ansible.builtin.import_tasks: config_postfix.yml

- name: dovecotのコンフィグ設定
  ansible.builtin.import_tasks: config_dovecot.yml

- name: rspamdのコンフィグ設定
  ansible.builtin.import_tasks: config_rspamd.yml
  
