---
- name: OSの各種設定
  ansible.builtin.import_tasks: config_os.yml

- name: パッケージインストール
  ansible.builtin.import_tasks: install.yml
  tags: install

- name: postfixのコンフィグ設定
  ansible.builtin.import_tasks: config_postfix.yml

- name: dovecotのコンフィグ設定
  import_tasks: config_dovecot.yml

- name: opendkimのコンフィグ設定
  import_tasks: config_opendkim.yml

- name: opendmarcのコンフィグ設定
  import_tasks: config_opendmarc.yml
