---
- name: Add docker GPG key
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - autofs
      - bash-completion
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - git-crypt
      - hdparm
      - mariadb-client
      - postfix
      - rsyslog
      - unzip
      - vim
      - zip

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: yes

- name: autofs config (/etc/auto.master.d/direct.autofs)
  ansible.builtin.copy:
    dest: /etc/auto.master.d/direct.autofs
    content: |
      /-    /etc/auto.direct

- name: autofs config (/etc/auto.direct)
  ansible.builtin.copy:
    dest: /etc/auto.direct
    content: |
      /mnt/usbdisk -fstype=xfs,rw :/dev/disk/by-uuid/5e6ea472-4bf6-43f5-a51e-414284ab1b6e
      /mnt/usbdisk-backup -fstype=xfs,rw :/dev/disk/by-uuid/241a4727-188d-44e2-a975-648847037f94
