---
- name: postfix main.cfの設定
  ini_file:
    path: /etc/postfix/main.cf
    section: null
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  loop: "{{ postfix_main_config | dict2items }}"
  notify: restart postfix
  when: postfix_main_config is defined
