---
- name: postmap smtp_sasl_password_maps
  ansible.builtin.command: postmap /etc/postfix/smtp_sasl_password_maps

- name: postmap tls_server_sni_maps
  ansible.builtin.command: postmap -F /etc/postfix/tls_server_sni_maps

- name: restart postfix
  systemd:
    state: restarted
    name: postfix
  ignore_errors: '{{ ansible_check_mode }}'

- name: restart dovecot
  systemd:
    state: restarted
    name: dovecot
  ignore_errors: '{{ ansible_check_mode }}'

- name: restart opendkim
  systemd:
    state: restarted
    name: opendkim
  ignore_errors: '{{ ansible_check_mode }}'

- name: restart opendmarc
  systemd:
    state: restarted
    name: opendmarc
  ignore_errors: '{{ ansible_check_mode }}'
