---
- name: restart postfix
  systemd:
    state: restarted
    name: postfix

- name: restart dovecot
  systemd:
    state: restarted
    name: dovecot

- name: restart haproxy
  systemd:
    state: restarted
    name: haproxy
