---
- name: postmap smtp_sasl_password_maps
  ansible.builtin.command: postmap /etc/postfix/smtp_sasl_password_maps

- name: postmap tls_server_sni_maps
  ansible.builtin.command: postmap -F /etc/postfix/tls_server_sni_maps

- name: restart postfix
  systemd:
    state: restarted
    name: postfix

- name: restart dovecot
  systemd:
    state: restarted
    name: dovecot

- name: restart opendkim
  systemd:
    state: restarted
    name: opendkim
