---
- name: apply netplan
  ansible.builtin.command: netplan apply

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
